### PR TITLE
Ender 3 + BL Touch

### PR DESCRIPTION
**Pull request by Nordlaw-tech**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### CODE REVIEW

**Comment by mikeprevette** [comment]
Has anyone else tried this out?

**Comment by Nordlaw-tech** [comment]
Hello Mike

I’m new to github and this was probably a mistake as I download to my pc and mark for personal use. I can delete it if you want?

Thanks

Geoff

**Comment by turbotrix** [comment]
https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/pull/293/commits/b8eb290c2740e03476876d884f832b4b117398bc

**Comment by Gamester17** [comment]
@Nordlaw-tech suggest that you just close this pull request to start with and then later delete the branch after a while if no one objects.

**Pull request closed without merging**
